Longer wait period

diff --git a/firstJenkinsProject/Jenkinsfile b/firstJenkinsProject/Jenkinsfile
--- a/firstJenkinsProject/Jenkinsfile
+++ b/firstJenkinsProject/Jenkinsfile
@@ -3,31 +3,26 @@ pipeline {
     stages {
         stage('Build') {
             options {
-                timeout(time: 1, unit: "SECONDS")
+                timeout(time: 3, unit: "SECONDS")
             }
             steps {
-                try {
+                sh 'echo "Checking files"'
+                sh '''
+                    #!/bin/sh
+                    ls -la
                     echo "Go to sleep for 2s"
                     sleep(time: 2, unit: "SECONDS")
                     echo "awake"
-                    sh 'echo "Checking files"'
-                    sh '''
-                        #!/bin/sh
-                        ls -la
-                        echo "Checking fit"
-                        if (grep -rnw 'firstJenkinsProject/test' -e 'fit(') || (grep -rnw 'firstJenkinsProject/test' -e 'fdescribe(')
-                        then
-                            echo "Should fail"
-                            exit 1
-                        else
-                            echo "We are clean"
-                        fi
-                        echo "end"
-                    '''
-                } catch (Throwable e) {
-                    echo "Caught ${e.toString()}"
-                    currentBuild.result = "SUCCESS" 
-                }
+                    echo "Checking fit"
+                    if (grep -rnw 'firstJenkinsProject/test' -e 'fit(') || (grep -rnw 'firstJenkinsProject/test' -e 'fdescribe(')
+                    then
+                        echo "Should fail"
+                        exit 1
+                    else
+                        echo "We are clean"
+                    fi
+                    echo "end"
+                '''
             }
         }
         stage('2nd Step') {
